[[bin]]
name = 'two-sum'
path = 'src/0001.two-sum/solution.rs'

[[bin]]
name = 'longest-substring-without-repeating-characters'
path = 'src/0003.longest-substring-without-repeating-characters/solution.rs'

[[bin]]
name = 'container-with-most-water'
path = 'src/0011.container-with-most-water/solution.rs'

[[bin]]
name = '3sum'
path = 'src/0015.3sum/solution.rs'

[[bin]]
name = 'valid-parentheses'
path = 'src/0020.valid-parentheses/solution.rs'

[[bin]]
name = 'merge-two-sorted-lists'
path = 'src/0021.merge-two-sorted-lists/solution.rs'

[[bin]]
name = 'generate-parentheses'
path = 'src/0022.generate-parentheses/solution.rs'

[[bin]]
name = 'search-in-rotated-sorted-array'
path = 'src/0033.search-in-rotated-sorted-array/solution.rs'

[[bin]]
name = 'valid-sudoku'
path = 'src/0036.valid-sudoku/solution.rs'

[[bin]]
name = 'trapping-rain-water'
path = 'src/0042.trapping-rain-water/solution.rs'

[[bin]]
name = 'group-anagrams'
path = 'src/0049.group-anagrams/solution.rs'

[[bin]]
name = 'search-a-2d-matrix'
path = 'src/0074.search-a-2d-matrix/solution.rs'

[[bin]]
name = 'sort-colors'
path = 'src/0075.sort-colors/solution.rs'

[[bin]]
name = 'minimum-window-substring'
path = 'src/0076.minimum-window-substring/solution.rs'

[[bin]]
name = 'remove-duplicates-from-sorted-array-ii'
path = 'src/0080.remove-duplicates-from-sorted-array-ii/solution.rs'

[[bin]]
name = 'largest-rectangle-in-histogram'
path = 'src/0084.largest-rectangle-in-histogram/solution.rs'

[[bin]]
name = 'same-tree'
path = 'src/0100.same-tree/solution.rs'

[[bin]]
name = 'binary-tree-level-order-traversal'
path = 'src/0102.binary-tree-level-order-traversal/solution.rs'

[[bin]]
name = 'maximum-depth-of-binary-tree'
path = 'src/0104.maximum-depth-of-binary-tree/solution.rs'

[[bin]]
name = 'balanced-binary-tree'
path = 'src/0110.balanced-binary-tree/solution.rs'

[[bin]]
name = 'best-time-to-buy-and-sell-stock'
path = 'src/0121.best-time-to-buy-and-sell-stock/solution.rs'

[[bin]]
name = 'valid-palindrome'
path = 'src/0125.valid-palindrome/solution.rs'

[[bin]]
name = 'longest-consecutive-sequence'
path = 'src/0128.longest-consecutive-sequence/solution.rs'

[[bin]]
name = 'reorder-list'
path = 'src/0143.reorder-list/solution.rs'

[[bin]]
name = 'evaluate-reverse-polish-notation'
path = 'src/0150.evaluate-reverse-polish-notation/solution.rs'

[[bin]]
name = 'find-minimum-in-rotated-sorted-array'
path = 'src/0153.find-minimum-in-rotated-sorted-array/solution.rs'

[[bin]]
name = 'min-stack'
path = 'src/0155.min-stack/solution.rs'

[[bin]]
name = 'two-sum-ii-input-array-is-sorted'
path = 'src/0167.two-sum-ii-input-array-is-sorted/solution.rs'

[[bin]]
name = 'number-of-islands'
path = 'src/0200.number-of-islands/solution.rs'

[[bin]]
name = 'reverse-linked-list'
path = 'src/0206.reverse-linked-list/solution.rs'

[[bin]]
name = 'contains-duplicate'
path = 'src/0217.contains-duplicate/solution.rs'

[[bin]]
name = 'invert-binary-tree'
path = 'src/0226.invert-binary-tree/solution.rs'

[[bin]]
name = 'lowest-common-ancestor-of-a-binary-search-tree'
path = 'src/0235.lowest-common-ancestor-of-a-binary-search-tree/solution.rs'

[[bin]]
name = 'product-of-array-except-self'
path = 'src/0238.product-of-array-except-self/solution.rs'

[[bin]]
name = 'sliding-window-maximum'
path = 'src/0239.sliding-window-maximum/solution.rs'

[[bin]]
name = 'valid-anagram'
path = 'src/0242.valid-anagram/solution.rs'

[[bin]]
name = 'top-k-frequent-elements'
path = 'src/0347.top-k-frequent-elements/solution.rs'

[[bin]]
name = 'longest-repeating-character-replacement'
path = 'src/0424.longest-repeating-character-replacement/solution.rs'

[[bin]]
name = 'diameter-of-binary-tree'
path = 'src/0543.diameter-of-binary-tree/solution.rs'

[[bin]]
name = 'permutation-in-string'
path = 'src/0567.permutation-in-string/solution.rs'

[[bin]]
name = 'subtree-of-another-tree'
path = 'src/0572.subtree-of-another-tree/solution.rs'

[[bin]]
name = 'maximum-product-of-three-numbers'
path = 'src/0628.maximum-product-of-three-numbers/solution.rs'

[[bin]]
name = 'binary-search'
path = 'src/0704.binary-search/solution.rs'

[[bin]]
name = 'daily-temperatures'
path = 'src/0739.daily-temperatures/solution.rs'

[[bin]]
name = 'longest-mountain-in-array'
path = 'src/0845.longest-mountain-in-array/solution.rs'

[[bin]]
name = 'car-fleet'
path = 'src/0853.car-fleet/solution.rs'

[[bin]]
name = 'koko-eating-bananas'
path = 'src/0875.koko-eating-bananas/solution.rs'

[[bin]]
name = 'time-based-key-value-store'
path = 'src/0981.time-based-key-value-store/solution.rs'

[[bin]]
name = 'cinema-seat-allocation'
path = 'src/1386.cinema-seat-allocation/solution.rs'

[[bin]]
name = 'shortest-and-lexicographically-smallest-beautiful-string'
path = 'src/2904.shortest-and-lexicographically-smallest-beautiful-string/solution.rs'

[[bin]]
name = 'find-the-largest-almost-missing-integer'
path = 'src/3471.find-the-largest-almost-missing-integer/solution.rs'

[[bin]]
name = 'maximum-product-of-two-digits'
path = 'src/3536.maximum-product-of-two-digits/solution.rs'

[[bin]]
name = 'check-divisibility-by-digit-sum-and-product'
path = 'src/3622.check-divisibility-by-digit-sum-and-product/solution.rs'

[dependencies]
anyhow = '1.0.79'
leetgo-rs = '0.2.1'
serde = '1.0.196'
serde_json = '1.0.113'

[package]
edition = '2024'
name = 'leetcode-solutions'
version = '0.1.0'
